from machine import Pin
from utime import sleep
red = Pin(15, Pin.OUT)
green = Pin(14, Pin.OUT)
blue = Pin(13, Pin.OUT)
red.value(0)
green.value(0)
blue.value(0)
print("hello world, from github")
while True:
  blue.value(0)
  red.value(1)
  sleep(0.5)
  green.value(1)
  sleep(0.5)
  red.value(0)
  sleep(0.5)
  blue.value(1)
  sleep(0.5)
  green.value(0)
  sleep(0.5)
  red.value(1)
  sleep(0.5)
